#spring.application.name=ms-catalog

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/ms_catalog
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/doc/swagger-ui.html

spring:
  application:
    name: ms-catalog-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070





