server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
    cloud:
      gateway:
        discovery:
          locator:
            enable: true
        routes:
          - id: ms-catalog-service
            uri: lb://ms-catalog-service
            predicates:
              - Path=/category/**, /product/**

          - id: ms-client-service
            uri: lb://ms-client-service
            predicates:
              - Path=/client/**

          - id: ms-order-service
            uri: lb://ms-order-service
            predicates:
              - Path=/order/**
